{"uuid": "219f3e4f-1183-4fc2-afab-0d7e5d6defe5", "children": ["ceca8ad3-09c6-43e2-b981-91c9fe564586", "2c0924d5-9d13-46a5-b371-a7be29010497", "f91ab7f2-4163-436d-9a89-83f2c3bee7cb"], "befores": [{"name": "_Class__pytest_setup_class", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.\n\n", "trace": "  File \"/usr/local/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.7/site-packages/_pytest/fixtures.py\", line 937, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/_pytest/fixtures.py\", line 790, in call_fixture_func\n    res = next(it)\n  File \"/usr/local/lib/python3.7/site-packages/_pytest/python.py\", line 760, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"/usr/local/lib/python3.7/site-packages/_pytest/python.py\", line 701, in _call_with_optional_argument\n    func(arg)\n  File \"/scipt/python/testerhome_pratice/appium_homework/test_xueqiu_webview.py\", line 24, in setup_class\n    cls.driver.find_element_by_xpath(\"//*[@text='交易']\").click()\n  File \"/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 394, in find_element_by_xpath\n    return self.find_element(by=By.XPATH, value=xpath)\n  File \"/usr/local/lib/python3.7/site-packages/appium/webdriver/webdriver.py\", line 270, in find_element\n    'value': value})['value']\n  File \"/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/usr/local/lib/python3.7/site-packages/appium/webdriver/errorhandler.py\", line 29, in check_response\n    raise wde\n  File \"/usr/local/lib/python3.7/site-packages/appium/webdriver/errorhandler.py\", line 24, in check_response\n    super(MobileErrorHandler, self).check_response(response)\n  File \"/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1558364144168, "stop": 1558364165339}], "start": 1558364144168, "stop": 1558364165901}